version: '3'

services:
  postgres:
    build:
      context: ../databasepsql
    ports:
      - "5432:5432"
    networks:
      - todonetwork

  backend:
    build:
      context: ../backend
    environment:
      - DB_HOST=backend
      - DB_CONNECTION_STRING=postgres://psqlman:9cAN5M6J4x9M5Ly7qC@postgres:5432/TodoDB
    ports:
      - "9988:9988"
    networks:
      - todonetwork
    depends_on:
      - postgres

  frontend:
    build:
      context: ../distributedsystemsproject
    ports:
      - "80:80"
    networks:
      - todonetwork
    depends_on:
      - backend

networks:
  todonetwork:
    driver: bridge
